const constants = {
    ACTIONS : {
        GET_COUPON:'GET_COUPON',
        SET_PRICE_OBJ:'SET_PRICE_OBJ',
        BOOKING_SUCCESS:'BOOKING_SUCCESS',
        PAYMENT_SUCCESS:'PAYMENT_SUCCESS',
        RAZORPAY_SUCESS: 'RAZORPAY_SUCESS',
        CLEAR_BOOKING_RESPONSE: 'CLEAR_BOOKING_RESPONSE',
        SAVE_COUPON_DETAIL: 'SAVE_COUPON_DETAIL',
        CLEAR_COUPONOBJ_RESPONSE: 'CLEAR_COUPONOBJ_RESPONSE',
        SAVE_REDCASH_DETAILS: 'SAVE_REDCASH_DETAILS'
    }
}
export default constants;