module.exports = {
  LOGIN: '/notification/send_otp/',
  LOGOUT: '',
  USER: '/auth/shortprofile/',
  RECEIVEOTP: '/notification/send_otp/',
  VERIFYOTP: '/auth/users/otplogin/',
  ALLPHLEBOLIST: '/panel/data/',
  SAMPLEHANDOVER: '/phlebo/sample_handover/',
  EDITSAMPLEHANDOVER: '/phlebo/sample_handover/1/',
  PACKAGES: '/package/crmdata/',
  CITY: '/core/cities/',
  EDITPROFILE: '/auth/users/',
  LEADGENRATION: '/lead/generate-lead-by-user/',
  BANNER: '/blog/banner/',
  CUSTOMERBOOKINGDETAILS: '/booking/customer_booking/',
  DOWNLOAD: '/booking/report_status/',
  PINCODE: '/phlebo/pincode/',
  CITY_ID: '/phlebo/pincode/',
  MYCART: '/cart/',
  ADDRESS: '/address/',
  ADDADDRESS: '',
  COUPON: '/coupon/data/',
  ADDRESS: '/auth/address/',
  EDITADDRESS: '/auth/address/',
  BOOKING_SLOT_COLLECTION_DATE: '/booking/booking_slot_collection_date/',
  CREATE_BOOKING: '/booking/customer/create/',
  CART: '/cart/',
  PAYMENT: '/payment/order_payment/',
  PHLEBOLOC: '/booking/phlebo_loc/',
  PLAN_DETAIL: '/package/data_web/',
  PARAMETERS: '/package/pack-parameter/',
  RSIKAREA: '/package/tags/',
  UPLOAD_PRESCREPTION: '/booking/prescription_upload/',
  REDCASH: '/coupon/redcash/',
  REDCASHDETAILS: '/coupon/redcashdetails/',
  MYPRESCREPTION: '/booking/prescription_upload/',
  RESETPASSWORD: '/notification/send_otp/',
  TOKENSAVE: '/notification/token_save/',
  NEWLOGIN: '/auth/users/login/',
  NEW_PASSWORD: '/auth/resetpass/',
  ALREADY_LOGIN: '/auth/already/',
  NEW_USER_PASSWORD: '/auth/password_reset/reset_password/',
  IMAGANING_PACKAGE: '/package/data_web/imaging/',
  ////////////////////////////////
  CREATE_REMINDER: '/redoapp/create-reminder/',
  GET_REMINDER: '/redoapp/data/',
  CREATE_MANUAL: '/redoapp/manual/create/',
  EDIT_MANUAL: '/redoapp/manual/edit/',
  GET_MANUAL: '/redoapp/manual/',
  MONITOR_FEED:'/redoapp/moniter_feed/',
  BLOODGLU_GENLEAD:'/lead/generate-lead-by-user/',
  POST_MEAL : '/redoapp/calories_counter/create/',
  CREATE_USER:'/redoapp/update-create-unique-customer/',
  GETUSER_DETAILS:'/redoapp/get-unique-customer/',
  GET_REC_WEIGHT:'/redoapp/recomended-weight/?',
  GET_REC_PRECENT:'/redoapp/get-recomended-percent/',
  ADD_WEIGHT:'/redoapp/weight-create/',
  SEARCH_FOOD:'/redoapp/search_meal/?search=',
  SEARCH_FOOD_DETAILS:'/redoapp/search_meal_details/?search=',
  FOOD_UNITS:'/redoapp/food-units/?food_id=',
  ADD_FOOD:'/redoapp/add-food-with-measurement/',
  GET_FOOD:'/redoapp/add-food-with-measurement-list/?meal_date=',
  UPDATE_DELETE_FOOD:'/redoapp/delete-update-food/',
  GET_ESTIMATED_DATE:'/redoapp/get-estimate-date/',
};
