const constants = {
    ACTIONS : {
        SAVE_USER_DETAILS : 'SAVE_USER_DETAILS',
        POST_PUNCH_OUT : 'POST_PUNCH_OUT',
        CLEAR_DATA:'CLEAR_DATA',
        RESEND_OTP_RESPONSE:'RESEND_OTP_RESPONSE',
        GET_PUNCH_IN_DETAILS:'GET_PUNCH_IN_DETAILS',
        RESET_PASSWORD : 'RESET_PASSWORD',
        SAVE_LOGIN : 'SAVE_LOGIN',
        ERROR_IN_OTP : 'ERROR_IN_OTP',
        ALREADY_USER : 'ALREADY_USER',
        CLEAR_USER_RESPONSE : 'CLEAR_USER_RESPONSE',
    }
}
export default constants;